# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pZ5N7IX-N13opt6npqzlYRv6Fc8KyFoS
"""

with open("/content/it.50.txt","r") as f:
  content=f.read()
print(content)

with open("/content/frd.txt","r") as f:
  content=f.read()
  print(content)



with open("/content/it.50.txt","r") as f:
  content=f.readline()
print(content)



with open("/content/it.50.txt","r") as f:
   cont=f.readlines()
print(cont)

count

"""write =delete everryone"""

with open("/content/it.50.txt","w")as f:
  f.write("hello")

with open("/content/it.50.txt","r") as f:
   cont=f.readlines()
print(cont)

"""try and except"""

try:
    num1 = int(input("Enter first number: "))
    num2 = int(input("Enter second number: "))
    result = num1 / num2
    print("Result:", result)

except ZeroDivisionError:
    print("Error: Cannot divide by zero")

except ValueError:
    print("Error: Please enter valid numbers")

"""READ AND WRITE  CSV FILE"""

with open("/content/annual-enterprise-survey-2024-financial-year-provisional.csv", "r") as file:
    reader = csv.reader(file)

    for row in reader:
        print(row)